
mybatis:
  type-aliases-package: org.paboo.uranus.entity
  mapper-locations: classpath:mapping/*Mapping.xml
  configuration:
    logImpl: org.apache.ibatis.logging.slf4j.Slf4jImpl # mybatis sql log
    mapUnderscoreToCamelCase: true

